---
#HTTPD Yaml Playbook
- hosts: demo      
  user: ansible
  become: yes              
  connection: ssh
  tasks: 
    - name: Install httpd on amzn linux
      action: yum pkg=httpd state=installed
...
