# Loop Playbook
- hosts: myservers
  become: yes
  tasks:
    - name: add a list of users
      user: name='{{item}}' state=present
      with_items: 
        - ajay
        - harshita
        - shiva
	      - ganesh
	      - parvati
...
